<?php

namespace Database\Seeders;

use Dotenv\Util\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SidebarNavSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => null,
                'name' => 'Dashboard',
                'icon' => 'bi bi-grid',
                'url' => 'Dashboard',
                'order' => 1,
                'is_collapsed' => 0,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => null,
                'create_date' => null,
                'update_by' => '5',
                'update_date' => '2024-09-09 11:24:36',
            ],
            [
                'id' => 2,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => null,
                'name' => 'POS',
                'icon' => 'bi bi-grid',
                'url' => 'POS',
                'order' => 2,
                'is_collapsed' => 0,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => null,
                'create_date' => null,
                'update_by' => '5',
                'update_date' => '2024-09-09 11:24:36',
            ],
            [
                'id' => 3,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => null,
                'name' => 'Web Setup',
                'icon' => 'bi bi-grid',
                'url' => 'POS',
                'order' => 3,
                'is_collapsed' => 0,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => null,
                'create_date' => null,
                'update_by' => '5',
                'update_date' => '2024-09-09 11:24:36',
            ],
            [
                'id' => 4,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => 3,
                'name' => 'Side Menu',
                'icon' => 'bi bi-circle',
                'url' => 'SidebarNav',
                'order' => 1,
                'is_collapsed' => 0,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => null,
                'create_date' => null,
                'update_by' => null,
                'update_date' => null,
            ],
            [
                'id' => 5,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => 3,
                'name' => 'Brand',
                'icon' => 'bi bi-circle',
                'url' => 'Brand',
                'order' => 2,
                'is_collapsed' => 0,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => null,
                'create_date' => null,
                'update_by' => null,
                'update_date' => null,
            ],
            [
                'id' => 6,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => null,
                'name' => 'Product Setup',
                'icon' => 'bi bi-folder-check',
                'url' => '#',
                'order' => 4,
                'is_collapsed' => 1,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => '4',
                'create_date' => '2024-09-03 09:46:04',
                'update_by' => null,
                'update_date' => null,
            ],
            [
                'id' => 7,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => 6,
                'name' => 'Pro. Category',
                'icon' => 'bi bi-circle',
                'url' => 'ProCategory',
                'order' => 2,
                'is_collapsed' => 0,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => '4',
                'create_date' => '2024-09-03 09:47:58',
                'update_by' => '4',
                'update_date' => '2024-09-03 09:49:30',
            ],
            [
                'id' => 8,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => 6,
                'name' => 'Pro. Sub-Category',
                'icon' => 'a',
                'url' => 'ProSubCategory',
                'order' => 3,
                'is_collapsed' => 0,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => '4',
                'create_date' => '2024-09-03 09:50:04',
                'update_by' => null,
                'update_date' => null,
            ],
            [
                'id' => 9,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => 6,
                'name' => 'Pro. Type',
                'icon' => 'bi',
                'url' => 'ProType',
                'order' => 4,
                'is_collapsed' => 0,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => '4',
                'create_date' => '2024-09-03 09:48:37',
                'update_by' => null,
                'update_date' => null,
            ],
            [
                'id' => 10,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => 6,
                'name' => 'Product Info',
                'icon' => 'a',
                'url' => 'ProInfo',
                'order' => 5,
                'is_collapsed' => 0,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => '4',
                'create_date' => '2024-09-03 09:50:39',
                'update_by' => null,
                'update_date' => null,
            ],
            [
                'id' => 11,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => null,
                'name' => 'User Config',
                'icon' => 'bi bi-people-fill',
                'url' => '#',
                'order' => 5,
                'is_collapsed' => 1,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => '1010',
                'create_date' => '2024-09-01 08:26:21',
                'update_by' => '1010',
                'update_date' => '2024-09-01 08:56:26',
            ],
            [
                'id' => 12,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => 10,
                'name' => 'Branch Info',
                'icon' => 'bi bi-person-lines-fill',
                'url' => 'BranchInfo',
                'order' => 1,
                'is_collapsed' => 0,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => '1010',
                'create_date' => '2024-09-01 08:49:27',
                'update_by' => '1010',
                'update_date' => '2024-09-01 09:05:44',
            ],
            [
                'id' => 13,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => 10,
                'name' => 'User Info',
                'icon' => 'bi bi-person-lines-fill',
                'url' => 'User',
                'order' => 2,
                'is_collapsed' => 0,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => '1010',
                'create_date' => '2024-09-01 08:50:26',
                'update_by' => '1010',
                'update_date' => '2024-09-01 12:12:16',
            ],
            [
                'id' => 14,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => 10,
                'name' => 'User Roles',
                'icon' => 'bi bi-person-lines-fill',
                'url' => 'Roles',
                'order' => 3,
                'is_collapsed' => 0,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => '1010',
                'create_date' => '2024-09-01 08:51:46',
                'update_by' => '1010',
                'update_date' => '2024-09-01 11:48:57',
            ],
            [
                'id' => 15,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => 10,
                'name' => 'Permission',
                'icon' => 'bi',
                'url' => 'Permission',
                'order' => 5,
                'is_collapsed' => 0,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => '1010',
                'create_date' => '2024-09-01 08:52:12',
                'update_by' => '4',
                'update_date' => '2024-09-03 06:58:53',
            ],
            [
                'id' => 16,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => 10,
                'name' => 'Pro. Brand',
                'icon' => 'bi bi-circle',
                'url' => 'ProBrand',
                'order' => 1,
                'is_collapsed' => 0,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => '4',
                'create_date' => '2024-09-03 09:47:57',
                'update_by' => null,
                'update_date' => null,
            ],
            [
                'id' => 17,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => null,
                'name' => 'Header Page',
                'icon' => '',
                'url' => '',
                'order' => 6,
                'is_collapsed' => null,
                'is_heading' => 1,
                'status' => 'A',
                'create_by' => null,
                'create_date' => null,
                'update_by' => null,
                'update_date' => null,
            ],
            [
                'id' => 18,
                'uid' => \Illuminate\Support\Str::uuid(),
                'parent_id' => null,
                'name' => 'Profile',
                'icon' => 'bi bi-person',
                'url' => 'welcome',
                'order' => 7,
                'is_collapsed' => null,
                'is_heading' => 0,
                'status' => 'A',
                'create_by' => null,
                'create_date' => null,
                'update_by' => null,
                'update_date' => null,
            ],

        ];
        DB::table('sms_web_sidebar_menu')->insert($data);
    }
}
